server:
  port: 8282
  servlet:
    context-path: /intermine
    error:
      whitelabel:
        enabled: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/<your-database-name>?createDatabaseIfNotExist=true
    username: <database-username>
    password: <database-password>
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

  thymeleaf:
    cache: false

logging:
  level:
    org:
      hibernate:
        type: trace

